[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Tag               docker.*
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    DB                /fluent-bit/state/flb_container.db
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Refresh_Interval  5

[FILTER]
    Name          parser
    Match         docker.*
    Key_Name      log
    Parser        gophprofile_json
    Reserve_Data  On
    Preserve_Key  On

[FILTER]
    Name   grep
    Match  docker.*
    Regex  service ^gophprofile-(server|worker)$

[OUTPUT]
    Name                opensearch
    Match               docker.*
    Host                opensearch
    Port                9200
    Index               gophprofile-logs
    Logstash_Format     On
    Logstash_Prefix     gophprofile-logs
    Suppress_Type_Name  On
    Replace_Dots        On
    Trace_Error         On