{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.secretName" . }}
  namespace: {{ include "gophprofile.namespace" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  GOPHPROFILE_DATABASE_DSN: {{ required "secret.databaseDSN is required when secret.create=true" .Values.secret.databaseDSN | quote }}
  GOPHPROFILE_S3_ACCESS_KEY: {{ required "secret.s3AccessKey is required when secret.create=true" .Values.secret.s3AccessKey | quote }}
  GOPHPROFILE_S3_SECRET_KEY: {{ required "secret.s3SecretKey is required when secret.create=true" .Values.secret.s3SecretKey | quote }}
  GOPHPROFILE_RABBITMQ_URL: {{ required "secret.rabbitmqURL is required when secret.create=true" .Values.secret.rabbitmqURL | quote }}
{{- end }}