apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gophprofile-server-ingress
  namespace: gophprofile
  labels:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/instance: gophprofile
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: gophprofile
    app.kubernetes.io/managed-by: kubectl
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gophprofile
      app.kubernetes.io/instance: gophprofile
      app.kubernetes.io/component: server
  policyTypes:
    - Ingress
  ingress:
    # Разрешаем входящий HTTP-трафик от ingress-controller.
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 8080

    # Разрешаем scraping метрик от Prometheus Operator,
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8080