apiVersion: v1
kind: Service
metadata:
  name: gophprofile-server
  namespace: gophprofile
  labels:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/instance: gophprofile
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: gophprofile
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/instance: gophprofile
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: http
      protocol: TCP